### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by MaluNoPeleke** [indiependente/autoEqMac#6]
I have installed go with homebrew and tried to use autoEqMac on current macOS BigSur. I can run it and select a headphone but when I confirm it I get the following error:

`You selected: Beyerdynamic Custom One Pro (step 3)
panic: runtime error: index out of range [5] with length 3

goroutine 1 [running]:
github.com/indiependente/autoEqMac/autoeq.ToFixedBandEQs(0xc0002aea00, 0x1dc, 0x200, 0xc0004b2c30, 0x24, 0xc000287dc0, 0x1f, 0xc000129300)
	/home/runner/work/autoEqMac/autoEqMac/autoeq/fixed_band.go:29 +0x4fc
github.com/indiependente/autoEqMac/server.HTTPServer.GetFixedBandEQPreset(0x1476cc0, 0x169a8c0, 0x1477580, 0xc00000c4e0, 0x147a980, 0xc000010f30, 0x14775a0, 0xc000010f40, 0xc00005f470, 0xc00005f4a0, ...)
	/home/runner/work/autoEqMac/autoEqMac/server/server.go:97 +0x412
main.run(0x0, 0x0)
	/home/runner/work/autoEqMac/autoEqMac/main.go:71 +0xa32
main.main()
	/home/runner/work/autoEqMac/autoEqMac/main.go:32 +0x25`

I have tried it with the 0.1.0 release.

**Comment by MaluNoPeleke** [comment]
Tried it with the deps-upgrade branch and works there.
